# Generated by Django 4.2.1 on 2023-08-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservicerequest',
            name='service_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
